services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: kmm-backend
    container_name: kmm-backend
    ports:
      - "8081:8081"
    networks:
      - kmm-network
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: kmm-frontend
    container_name: kmm-frontend
    ports:
      - "8080:8080"
    networks:
      - kmm-network
    depends_on:
      - backend

networks:
  kmm-network:
    driver: bridge 