version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kmm-backend
    ports:
      - "8081:8081"
    networks:
      - kmm-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: kmm-frontend
    ports:
      - "8080:8080"
    networks:
      - kmm-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  kmm-network:
    driver: bridge

volumes:
  # Optional: persist logs or other data
  backend-logs:
    name: kmm-backend-logs
  frontend-logs:
    name: kmm-frontend-logs 