version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kmm-backend-prod
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    networks:
      - kmm-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: kmm-frontend-prod
    ports:
      - "8080:8080"
    networks:
      - kmm-network
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  kmm-network:
    driver: bridge

volumes:
  backend-logs:
    name: kmm-backend-logs-prod
  frontend-logs:
    name: kmm-frontend-logs-prod 