services:
  backend:
    build:
      platforms:
        - linux/amd64
      args:
        - NODE_ENV=production
    image: us-central1-docker.pkg.dev/kmm-app-20250616-151000/kmm-images/kmm-backend
    container_name: kmm-backend-build
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    
  frontend:
    build:
      platforms:
        - linux/amd64
      args:
        - BACKEND_URL=${BACKEND_URL:-http://localhost:8081}
        - NODE_ENV=production
    image: us-central1-docker.pkg.dev/kmm-app-20250616-151000/kmm-images/kmm-frontend
    container_name: kmm-frontend-build
    environment:
      - NODE_ENV=production 