name: KMM Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kotlin-multiplatform:
    name: Build KMM Targets
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build common module
      run: ./gradlew :shared:build
      
    - name: Test common module
      run: ./gradlew :shared:test
      
    - name: Build WASM JS target
      run: ./gradlew :shared:wasmJsNodeTest
      
    - name: Build Android target
      run: ./gradlew :shared:testDebugUnitTest
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kmm-build-artifacts
        path: |
          shared/build/libs/
          shared/build/outputs/

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Kotlin linter (if configured)
      run: ./gradlew ktlintCheck || echo "ktlint not configured, skipping"
      continue-on-error: true
      
    - name: Run detekt (if configured)
      run: ./gradlew detekt || echo "detekt not configured, skipping"
      continue-on-error: true 